/**
 * Divine Observatory Cinema: Explore is a living celestial atlas, not a neutral card catalogue.
 * Each entry point keeps study type and source status distinct while inviting deeper navigation.
 */
import { ArrowRight, BookOpenText, Compass, Search, Sparkles, Stars } from "lucide-react";
import { Link } from "wouter";
import { ASSETS, knowledgeCategories, records } from "@/data/content";
import { Reveal } from "@/components/Reveal";

const featuredOrbits = [
  { route: "/scriptures", title: "Scripture universe", tamil: "சாஸ்திர உலகம்", detail: "Enter through bounded reader records and explicit edition status.", image: ASSETS.scripture, alt: "Illuminated manuscript archive under a celestial canopy", span: "explore-orbit--scripture" },
  { route: "/temples", title: "Temple journeys", tamil: "ஆலயப் பயணங்கள்", detail: "Meet place, architecture, and regional practice without inventing travel claims.", image: ASSETS.temple, alt: "Temple at twilight with a reflecting water tank", span: "explore-orbit--temple" },
  { route: "/ask-divya", title: "Ask Divya", tamil: "திவ்யாவிடம் கேளுங்கள்", detail: "Use a labelled local guide to turn a broad question into a careful next step.", image: ASSETS.ask, alt: "Luminous knowledge core in a midnight-blue atmosphere", span: "explore-orbit--ask" },
];

export default function Explore({ onSearch }: { onSearch: () => void }) {
  return <main id="main-content" className="page-main explore-cinema">
    <section className="explore-cinema-hero"><img src={ASSETS.heroDawn} alt="A luminous pilgrimage path opening beneath a celestial dawn" fetchPriority="high" /><div className="explore-cinema-hero__veil" /><div className="explore-cinema-hero__atlas" aria-hidden="true"><span /><span /><span /></div><div className="explore-cinema-hero__inner"><p className="scene-kicker"><Stars size={14} aria-hidden="true" />DivyaNexus knowledge atlas</p><p lang="ta">கேள்வியைத் தெளிவாக்கும் பாதை</p><h1>Find the path that makes a question more precise.</h1><p>Explore Vedic knowledge through distinct, connected study worlds. Each route keeps scripture, devotion, cultural practice, and reflective guidance separate enough to remain meaningful.</p><div className="cinema-hero__actions"><button className="button button--primary button--glow" onClick={onSearch}><Search size={16} aria-hidden="true" />Search the library</button><Link className="button button--glass" href="/ask-divya"><Sparkles size={16} aria-hidden="true" />Ask a question</Link></div><div className="explore-cinema-hero__legend"><span><i />Cited starter record</span><span><i />Editorial overview</span><span><i />In preparation</span></div></div></section>
    <section className="explore-passage"><p><Compass size={16} aria-hidden="true" />Start with the kind of knowledge you seek, not a generic answer.</p><Link href="/sources">Read the source method <ArrowRight size={15} aria-hidden="true" /></Link></section>
    <section className="explore-orbits"><Reveal className="explore-section-head"><div><p className="scene-kicker">Three constellations</p><h2>Enter the <em>knowledge</em> universe.</h2></div><p>These visual thresholds are not shortcuts to certainty. They are distinct doors into text, place, and guided reflection.</p></Reveal><div className="explore-orbit-grid">{featuredOrbits.map((orbit, index) => <Link key={orbit.route} href={orbit.route} className={`explore-orbit ${orbit.span}`}><img src={orbit.image} alt={orbit.alt} loading={index === 0 ? "eager" : "lazy"} /><div className="explore-orbit__veil" /><div className="explore-orbit__content"><span>0{index + 1}</span><p className="scene-kicker">{index === 0 ? "Textual study" : index === 1 ? "Place & practice" : "Guided reflection"}</p><h3>{orbit.title}</h3><p lang="ta">{orbit.tamil}</p><small>{orbit.detail}</small><b>Enter orbit <ArrowRight size={15} aria-hidden="true" /></b></div></Link>)}</div></section>
    <section className="explore-index"><Reveal className="explore-index__intro"><div><p className="scene-kicker"><BookOpenText size={14} aria-hidden="true" />Atlas index</p><h2>Ten paths, held in their own light.</h2></div><p>Choose an orbit below. Each route labels its present level of verification and avoids merging distinct traditions into an interchangeable content feed.</p></Reveal><div className="explore-index__list">{knowledgeCategories.map((category, index) => <Link key={category.route} href={category.route}><span>0{index + 1}</span><div><p>{category.motif}</p><h3>{category.title}</h3><small lang="ta">{category.tamil}</small></div><p>{category.detail}</p><ArrowRight size={17} aria-hidden="true" /></Link>)}</div></section>
    <section className="explore-records"><Reveal><div className="explore-records__head"><div><p className="scene-kicker">Recently opened starter records</p><h2>Begin with a cited lead.</h2></div><Link href="/scriptures">Open scripture routes <ArrowRight size={15} aria-hidden="true" /></Link></div></Reveal><div className="explore-records__rail">{records.slice(0, 6).map((record, index) => <Link href={`${record.route}?record=${record.id}`} key={record.id}><span>0{index + 1}</span><p>{record.category} · {record.source}</p><h3>{record.title}</h3><small lang="ta">{record.tamilTitle}</small><strong>{record.reference}</strong><ArrowRight size={15} aria-hidden="true" /></Link>)}</div></section>
  </main>;
}
